### ISSUE TITLE
Unable to Find Synthetic Query Generation Script

### ISSUE THREAD

**Issue by FareedKhan-dev** [snap-stanford/stark#12]
`STaRK` is extremely relevant and well-suited to our use case. We are currently working on replicating a benchmark approach similar to STaRK, but we are unable to find scripts that can be adjusted or reused to produce synthetic queries. Are these scripts not available in the GitHub repository?

**Comment by Wuyxin** [comment]
Hey thanks for the interest!!

They are not available in the repo currently. I do have some messy code and I am happy to send them for reference. Please contact shirwu@stanford.edu if that's sth helpful. The official data generation code may take a while for me to clean and push to the repo. 

Cheers

**Comment by FareedKhan-dev** [comment]
Thanks for the help! I just sent you an email. Looking forward to your response.
