### ISSUE TITLE
could you provide the topic entity in each sentence?

### ISSUE THREAD

**Issue by ToneLi** [snap-stanford/stark#8]

**Comment by Wuyxin** [comment]
Hi, are you referring to the paper topic (field) of STaRK-MAG?

**Comment by ToneLi** [comment]
the topic entity in the input sentence  (query) of  stark-mag,  STaRK-prime, and stark-amazon

**Comment by ToneLi** [comment]
thanks for that

**Comment by ToneLi** [comment]
The entity's surface name that appears in the sentence, such as 'Yuriy Norshteyn,' is shown below.
![image](https://github.com/snap-stanford/stark/assets/33856565/a5735e94-8001-4539-aa6c-21899f8d754a)
